### ISSUE TITLE
Test Container Build *Without* Publishing Image

### ISSUE THREAD

**Issue by zicklag** [banzaicloud/drone-kaniko#16]
Is there a way to use this plugin to build the Docker image *without* publishing it, so that it can be used to validate that pull requests to the image successfully build.

BTW this is an awesome plugin and *exactly* what I was looking for. Now I can build my Open Source Docker images on the Drone Cloud for free! :smiley: I created a [topic](https://discourse.drone.io/t/drone-plugin-to-build-docker-images-without-privileges/5072?u=zicklag) on the Drone forum to help people find it.

**Comment by bonifaido** [comment]
Thanks @zicklag for this, great idea. Anyhow, I think using unprivileged builds is still much better in any use cases ;)

**Comment by zicklag** [comment]
Yep, I like unprivileged much better, too. :)
