### ISSUE TITLE
Support additional Kaniko options

### ISSUE THREAD

**Issue by benjamin-bergia** [banzaicloud/drone-kaniko#24]
**Is your feature request related to a problem? Please describe.**
I am running an internal registry in my kubernetes cluster and as such I am not using SSL.
Kaniko seems to offer an `--insecure` option which is not available on this plugin.

**Describe the solution you'd like to see**
Kaniko doesn't seem to have that many [flags](https://github.com/GoogleContainerTools/kaniko#additional-flags) and it should be possible to support them all.

**Describe alternatives you've considered**
Instead of keeping `EXTRA_OPTS` itnernal expose it to the users. It kind of goes against the idea of having settings but that the only other solution.

**Additional context**

**Comment by sagikazarmark** [comment]
@benjamin-bergia thanks for opening this issue. Would you be up for submitting a PR? 🙂

**Comment by benjamin-bergia** [comment]
I might have some days next week to give it a go.

**Comment by benjamin-bergia** [comment]
Hi @sagikazarmark, I am sorry I spend a week on kaniko and despite all my changes I still can't get it to work for me.
I ended up moving to buildah and as such I won't be able to provide anything for this issue
