### ISSUE TITLE
Not caching the base layer?

### ISSUE THREAD

**Issue by vitobotta** [banzaicloud/drone-kaniko#25]
**Describe the bug**
Hi! I am trying this plugin now and have a problem. I can see that it pushes layers to Github Package Registry because it says so. However when the build starts it seems it tries to read from a local `/cache` directory for the first layer instead of the cache repo. I see this in the log:

```
INFO[0001] Resolved base name ubuntu:bionic to ubuntu:bionic
--
2 | INFO[0001] Resolved base name ubuntu:bionic to ubuntu:bionic
3 | INFO[0001] Downloading base image ubuntu:bionic
4 | 2019/10/07 17:36:07 No matching credentials were found, falling back on anonymous
5 |  
6 | INFO[0003] Error while retrieving image from cache: getting file info: stat /cache/sha256:1bbdea4846231d91cce6c7ff3907d26fca444fd6b7e3c282b90c7fe4251f9f86: no such file or directory
7 | INFO[0003] Downloading base image ubuntu:bionic
```
This means that every time it starts the build from scratch. Is there a way to avoid this and ensure that everything is cached? Thanks!

**Steps to reproduce the issue:**
Just set `cache: true`.

**Expected behavior**
I would expect the caching to cache the first layer as well, because otherwise the caching of following layers is very little useful.

**Comment by vitobotta** [comment]
Nevermind. I was missing the local "warmed" cache. I think I'll stick with the default Docker plugin for now, because I found a way to properly cache with it which works a lot better. I would like to use Kaniko but from searching it looks like it still has several issues (not just with caching). Thanks anyway :)

**Comment by servo1x** [comment]
Hi @vitobotta, care to share your alternative solution?

**Comment by vitobotta** [comment]
Hi @servo1x I wrote about it here https://vitobotta.com/2019/10/09/ci-cd-with-drone-for-deployment-to-kubernetes-with-helm/
