### ISSUE TITLE
Local Caching

### ISSUE THREAD

**Issue by captn3m0** [banzaicloud/drone-kaniko#8]
I was trying to create an equivalent plugin for [uber/makisu](https://github.com/uber/makisu#makisu-on-kubernetes), and while it supports remote caching (on the registry), the local caching requires a volume mount.

The kaniko docs also mention something similar: https://github.com/GoogleContainerTools/kaniko#caching-base-images

Just curious to know, have you considered setting this up in Drone somehow? Otherwise, the cache is only good if you have a local registry.

**Comment by bonifaido** [comment]
Hi @captn3m0,

we usually use it with a local registry (we use a Drone for which runs on top of Kubernetes), but I think you can use a local registry in a simple Docker based environment as well with the help of the `https://hub.docker.com/_/registry` image.

I haven't tried mounting a volume but using [Bind mounts](https://docs.drone.io/user-guide/pipeline/volumes/) in Drone should just work, right?

**Comment by captn3m0** [comment]
Bind Mounts need trusted repositories, which we are trying to avoid.

Thanks for the reply, I'll close this.

**Comment by servo1x** [comment]
Hi @bonifaido, do you sync the local registry between each Drone worker?

**Comment by bonifaido** [comment]
No, we don't do such a thing.
