### ISSUE TITLE
Support/example for gcr push using json key

### ISSUE THREAD

**Issue by rverma-nikiai** [banzaicloud/drone-kaniko#9]
Support/example for gcr push using json key

**Comment by bonifaido** [comment]
Hi @rverma-nikiai, thanks for reporting this, the GCR has been just added in https://github.com/banzaicloud/drone-kaniko/pull/10, it is released in the latest (0.3.0) image.

**Comment by bonifaido** [comment]
Very good idea, please check: https://github.com/banzaicloud/drone-kaniko/pull/11
